apiVersion: v2
name: onecx-search-config-ui
version: 0.0.0
description: onecx-search-config UI
home: https://github.com/onecx/onecx-search-config-ui
keywords:
  - onecx-search-config
sources:
  - https://github.com/onecx/onecx-search-config-ui
maintainers:
  - name: # ACTION: add name of maintainer
    email: # ACTION: add email of maintainer
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
