app:
  name: ui
  image:
    repository: 'onecx/onecx-search-config-ui'
  routing:
    enabled: true
    path: /mfe/onecxSearchConfig/

  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OnecxSearchConfigModule'
          description: 'OneCX OnecxSearchConfig Module'
          note: 'OneCX OnecxSearchConfig UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-search-config
          tagName: onecx-search-config-webcomponent
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: 'onecx-search-config-ui'
# PIPE Config
